# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "agent.baml": "function AgentStep(messages: Message[]) -> ContinueResearch | FinalResponse | AskUser {\n  client Ollama\n  prompt #\"\n    You are a helpful AI assistant in a Discord server. Based on the conversation history, decide your next action.\n\n    Available actions:\n    1. ContinueResearch - If you need to fetch information from URLs to answer the question. Provide URLs that would help answer the user's question.\n    2. FinalResponse - If you have enough information to provide a complete answer.\n    3. AskUser - If the user's request is unclear or you need them to choose between options.\n\n    Guidelines:\n    - Only use ContinueResearch if you genuinely need web content to answer\n    - Provide helpful, accurate responses\n    - If asking for clarification, provide 2-4 clear options\n    - Keep responses concise but informative\n\n    {{ ctx.output_format }}\n\n    Conversation history:\n    {% for msg in messages %}\n    [{{ msg.role }}]: {{ msg.content }}\n    {% endfor %}\n\n    Decide your next action:\n  \"#\n}\n",
    "clients.baml": "client<llm> Ollama {\n  provider openai\n  options {\n    base_url env.OLLAMA_URL\n    api_key \"ollama\" // Ollama doesn't require a real API key\n    model env.OLLAMA_MODEL\n  }\n}\n",
    "generators.baml": "generator target {\n  output_type python/pydantic\n  output_dir \"../baml_client\"\n  version \"0.215.2\"\n}\n",
    "types.baml": "// Message types for conversation history\nclass Message {\n  role \"user\" | \"assistant\" | \"tool\"\n  content string\n}\n\n// Tool definitions\nclass FetchUrlTool {\n  url string @description(\"The URL to fetch content from\")\n  reason string @description(\"Brief explanation of why this URL is relevant to the user's question\")\n}\n\n// Agent action types - the agent chooses one of these\nclass ContinueResearch {\n  reasoning string @description(\"Brief explanation of why more research is needed\")\n  tool_calls FetchUrlTool[] @description(\"List of URLs to fetch for more information\")\n}\n\nclass FinalResponse {\n  response string @description(\"The final response to send to the user\")\n}\n\nclass AskUser {\n  question string @description(\"The clarifying question to ask the user\")\n  options string[] @description(\"2-4 options for the user to choose from\")\n}\n",
}

def get_baml_files():
    return _file_map