# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class AskUser(BaseModel):
    question: typing.Optional[str] = None
    options: typing.List[str]

class ContinueResearch(BaseModel):
    reasoning: typing.Optional[str] = None
    tool_calls: typing.List["FetchUrlTool"]

class FetchUrlTool(BaseModel):
    url: typing.Optional[str] = None
    reason: typing.Optional[str] = None

class FinalResponse(BaseModel):
    response: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Optional[typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant'], typing_extensions.Literal['tool']]] = None
    content: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
