# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (12)
# #########################################################################

class AskUser(BaseModel):
    reasoning: str
    question: str
    options: typing.List[str]

class BashTool(BaseModel):
    command: str
    reason: str

class FetchUrlTool(BaseModel):
    url: str
    reason: str

class FinalAnswer(BaseModel):
    reasoning: str
    response: str

class GatherInformation(BaseModel):
    reasoning: str
    tool_calls: typing.List[typing.Union["FetchUrlTool", "GetOllamaModelsTool", "GetStoredContentTool", "TavilySearchTool"]]

class GetOllamaModelsTool(BaseModel):
    reason: str

class GetStoredContentTool(BaseModel):
    sha_key: str
    reason: str

class Message(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant'], typing_extensions.Literal['tool'], typing_extensions.Literal['error']]
    content: str

class PerformAction(BaseModel):
    reasoning: str
    tool_calls: typing.List[typing.Union["ReadFileTool", "WriteFileTool", "BashTool"]]

class ReadFileTool(BaseModel):
    file_path: str
    reason: str

class TavilySearchTool(BaseModel):
    query: str
    reason: str

class WriteFileTool(BaseModel):
    file_path: str
    content: str
    reason: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
