# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AskUser": types.AskUser,
    "stream_types.AskUser": stream_types.AskUser,

    "types.ContinueResearch": types.ContinueResearch,
    "stream_types.ContinueResearch": stream_types.ContinueResearch,

    "types.FetchUrlTool": types.FetchUrlTool,
    "stream_types.FetchUrlTool": stream_types.FetchUrlTool,

    "types.FinalResponse": types.FinalResponse,
    "stream_types.FinalResponse": stream_types.FinalResponse,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,


}